#!/usr/bin/env python3
"""Generate the SHARC SLEIGH spec from tools/sharc_visa_tables.py.

Hand-writing 47 constructors would drift from the transcription the moment
either changed. This emits them, so the table stays the single source of
truth and regenerating is the way to pick up encoding fixes.

Control-flow p-code is emitted for 8a, 9a, 9b, 11a, 25a_direct and
25a_pcrel. Deliberately excluded: 10a (its opcode mask constrains only 2
bits and its cond field is near-uniformly distributed in real firmware,
unlike the clear cond=31 spike genuine control-flow types show, so most
10a matches are not real instructions and making them indirect jumps
would corrupt the analysis); 11c and 25c_rframe (both `uncertain` in the
tables); and 25a_rframe (a frame-restore pseudo-op, not a branch). The
rel=1 (PC-relative reladdr6) forms of 9a/9b are not yet modelled, only
rel=0 (register-indirect). Everything else decodes to the right LENGTH
and prints its operands, which is what stops a walk desyncing.

The cond value meaning "always" differs by type: 31 for 8a/9a/9b, but 30
for 11a, whose opcode fixes bit 32 -- the low bit of its own cond field --
to 0, making 31 unencodable there.

Addressing: code addresses are 16-bit short-word units, so a program is
imported at byte base 2*<word address> and branch targets are doubled here.
A wordsize=2 space would be the natural spelling and silently matches
nothing -- see the module commit message.

    uv run python tools/ghidra/gen-sharc-slaspec.py > tools/ghidra/SHARC/data/languages/sharc.slaspec
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import sharc_visa_tables as T

HEAD = '''# SLEIGH specification for Analog Devices SHARC+ (ADSP-2156x) VISA.
# GENERATED by tools/ghidra/gen-sharc-slaspec.py -- do not edit by hand.
# Encodings come from tools/sharc_visa_tables.py (transcribed from the
# SHARC+ Core Programming Reference at 400 DPI). See that file for which
# entries are confirmed and which are not.
#
# A 48-bit instruction is three 16-bit words, each LITTLE-endian in memory,
# concatenated MOST-SIGNIFICANT WORD FIRST:
#     w0,w1,w2 = unpack('<3H'); insn = (w0<<32)|(w1<<16)|w2
# so insn bit N maps to w0 bit N-32, w1 bit N-16, w2 bit N.

define endian=little;
define alignment=2;

define space ram      type=ram_space      size=4 default;
define space register type=register_space size=4;

define register offset=0x00 size=4 [ PC ];
define register offset=0x10 size=4 [ R0  R1  R2  R3  R4  R5  R6  R7
                                     R8  R9  R10 R11 R12 R13 R14 R15 ];
define register offset=0x50 size=4 [ I0 I1 I2 I3 I4 I5 I6 I7 ];
define register offset=0x70 size=4 [ M0 M1 M2 M3 M4 M5 M6 M7 ];
# PCSTK: the hardware PC stack a return pops; nothing models that stack,
# so a return reads PCSTK and its value is always unknown.
# CC: a placeholder condition flag that nothing ever writes, so Ghidra
# treats a branch on it as genuinely conditional and explores both paths.
define register offset=0x90 size=4 [ PCSTK ];
define register offset=0x94 size=1 [ CC ];
'''

def tokens():
    out = []
    for w in (0, 1, 2):
        out.append('define token w%d (16)' % w)
        out.append('    w%d_all = (0,15)' % w)
        for b in range(16):
            out.append('    w%d_%d = (%d,%d)' % (w, b, b, b))
        if w == 0:
            out.append('    w0_cond40 = (0,4)')
            out.append('    w0_cond51 = (1,5)')
        if w == 1:
            out.append('    w1_pmi10 = (14,15)')
            out.append('    w1_pmi10lo = (14,15)')
            out.append('    w1_pmi10hi = (14,15)')
            out.append('    w1_pmm = (11,13)')
        out.append(';')
    out.append('attach variables [ w1_pmi10lo ] [ I0 I1 I2 I3 ];')
    out.append('attach variables [ w1_pmi10hi ] [ I4 I5 I6 I7 ];')
    return '\n'.join(out)

def word_of(bit, nbits):
    """-> (token index, bit position within that 16-bit word)."""
    top = nbits - 1                     # e.g. 47 for a 48-bit instruction
    w = (top - bit) // 16               # 0 = most significant word
    return w, bit % 16

def constraints(entry):
    """-> list per token index of constraint strings."""
    n = entry['bits']
    mask, val = entry['opcode_mask'], entry['opcode_value']
    per = {0: [], 1: [], 2: []}
    for bit in range(n):
        if (mask >> bit) & 1:
            w, p = word_of(bit, n)
            per[w].append('w%d_%d=%d' % (w, p, (val >> bit) & 1))
    return per


# `cond` value meaning "always", per type. 31 for the branch types, measured
# as their dominant value in real firmware (8a: 48.8% Digitakt / 47.2%
# Digitone; 9a: 83.7% / 44.8%). Type 11a cannot encode 31 at all -- its
# opcode fixes bit 32, the low bit of its own cond field, to 0 -- so its
# unconditional form is 30, which is likewise the measured dominant value
# there (87.5% of 11a returns on Digitakt).
ALWAYS_COND = {'8a': 31, '9a': 31, '9b': 31, '11a': 30}

def emit_control_flow(types_by_name):
    """-> (text, count) for the 8a/9a/9b/11a control-flow constructors.

    cond=ALWAYS_COND[type] means "always" (measured: it's the dominant cond
    value for 8a and 9a across both firmwares), so each variant below is
    emitted twice -- once with cond constrained to that value and
    unconditional p-code, once with cond unconstrained and `if (CC)` p-code.
    SLEIGH prefers the more-constrained match, so the constrained form wins
    when it applies.
    """
    lines = []
    count = 0

    # ---- 8a: branch to a 24-bit immediate (jump/call, absolute/relative) --
    e = types_by_name['8a']
    w0c = ' & '.join(constraints(e)[0])
    w1c = ' & '.join(constraints(e)[1])
    lines.append('A8abs: reloc is %s & w1_all ; w2_all' % w1c)
    lines.append('    [ reloc = ((w1_all & 0xff) << 17) + (w2_all << 1); ] { export *:4 reloc; }')
    lines.append('A8rel: reloc is %s & w1_all ; w2_all' % w1c)
    lines.append('    [ reloc = inst_start + (((((( w1_all & 0xff) << 16) + w2_all) ^ 0x800000) - 0x800000) * 2); ] { export *:4 reloc; }')
    count += 2
    for r, b, sub, act, mn in (
        (0, 0, 'A8abs', 'goto', 'jump'),
        (0, 1, 'A8abs', 'call', 'call'),
        (1, 0, 'A8rel', 'goto', 'jump'),
        (1, 1, 'A8rel', 'call', 'call'),
    ):
        rb = 'w0_8=%d & w0_7=%d' % (r, b)
        w0base = '%s & %s' % (w0c, rb) if w0c else rb
        lines.append(':%s %s is %s & w0_cond51=%d ; %s { %s %s; }' % (mn, sub, w0base, ALWAYS_COND['8a'], sub, act, sub))
        # SLEIGH only permits `goto` directly after `if`, so conditional
        # forms are spelled as a skip over the unconditional statement.
        lines.append(':if.%s %s is %s ; %s { if (CC == 0) goto inst_next; %s %s; }' % (mn, sub, w0base, sub, act, sub))
        count += 2

    # ---- 9a/9b: jump/call through a register (dispatch form). Only rel=0
    # (register-indirect) is modelled -- rel=1 reinterprets the same bits
    # as the PC-relative reladdr6, which is not handled here. pmm/Md is
    # ignored: it post-modifies the index register rather than changing
    # the branch target.
    for name in ('9a', '9b'):
        e = types_by_name[name]
        w0c = ' & '.join(constraints(e)[0])
        w1c = ' & '.join(constraints(e)[1])
        ntok = e['bits'] // 16
        for b, act, base_mn in ((0, 'goto', 'jump'), (1, 'call', 'call')):
            for pmi2, field in ((0, 'w1_pmi10lo'), (1, 'w1_pmi10hi')):
                mnemonic = base_mn + 'ind'
                rb5 = 'w0_8=0 & w0_7=%d & w0_5=%d' % (b, pmi2)
                w0always = '%s & %s' % (w0c, rb5) if w0c else rb5
                w1part = '%s & %s' % (w1c, field) if w1c else field
                if ntok == 3:
                    tail = ' ; %s ; w2_all' % w1part
                else:
                    tail = ' ; %s' % w1part
                lines.append(':%s %s is %s & w0_cond40=%d%s { %s [%s]; }' %
                              (mnemonic, field, w0always, ALWAYS_COND[name], tail, act, field))
                # SLEIGH only permits `goto` directly after `if`, so
                # conditional forms are spelled as a skip over the
                # unconditional statement.
                lines.append(':if.%s %s is %s%s { if (CC == 0) goto inst_next; %s [%s]; }' %
                              (mnemonic, field, w0always, tail, act, field))
                count += 2

    # ---- 11a: return. x (rts vs rti) is left unconstrained here, matching
    # the rest of this file's not-worrying-about-non-control-flow-fields
    # policy: both are control transfers off PCSTK.
    # 11c (the 16-bit return) and 25c_rframe stay excluded because they are
    # `uncertain` in the tables -- which is why function bounds stay poor:
    # only 40 of the 48-bit 11a returns appear in 224 KB of Digitakt code,
    # so most returns are the compact form this spec cannot yet see.
    e = types_by_name['11a']
    per = constraints(e)
    parts = [' & '.join(per[w]) or 'w%d_all' % w for w in range(3)]
    lines.append(':rts is %s & w0_cond40=%d ; %s ; %s { return [PCSTK]; }' %
                  (parts[0], ALWAYS_COND['11a'], parts[1], parts[2]))
    # SLEIGH only permits `goto` directly after `if`, so conditional forms
    # are spelled as a skip over the unconditional statement.
    lines.append(':if.rts is %s ; %s ; %s { if (CC == 0) goto inst_next; return [PCSTK]; }' %
                  (parts[0], parts[1], parts[2]))
    count += 2

    return '\n'.join(lines), count


def main():
    print(HEAD)
    print(tokens())
    print()
    print('# 24-bit absolute target, high 8 bits in w1 and low 16 in w2,')
    print('# doubled to turn a short-word address into this space\'s byte address.')
    print('Dest24: reloc is w1_15=0 & w1_14=0 & w1_13=0 & w1_12=0 & w1_11=0 & '
          'w1_10=0 & w1_9=0 & w1_8=0 & w1_all ; w2_all')
    print('    [ reloc = ((w1_all & 0xff) << 17) + (w2_all << 1); ] { export *:4 reloc; }')
    print()
    types_by_name = {e['name']: e for e in T.TYPES}
    cf_text, cf_count = emit_control_flow(types_by_name)
    print(cf_text)
    print()
    emitted = cf_count
    CF = {'25a_direct': ('cjump', 'call'), '25a_pcrel': ('cjump_pc', 'goto')}
    # 10a is NOT given control-flow p-code: its opcode mask constrains only
    # bits 47:46, and its cond field is near-uniformly distributed in real
    # firmware (top value 14.9%, the rest ~5% each) where genuine
    # control-flow types show a clear cond=31 spike -- so most 10a matches
    # are not real instructions, and making them indirect jumps would
    # corrupt the analysis. It keeps its plain NOP constructor below.
    HANDLED = {'8a', '9a', '9b', '11a'}
    for e in T.TYPES:
        name = e['name']
        if e.get('uncertain'):
            continue
        if not e.get('opcode_mask'):
            continue
        if name in HANDLED:
            # real p-code for these was already emitted by emit_control_flow()
            continue
        n = e['bits']
        per = constraints(e)
        ntok = n // 16
        if name in CF:
            # target lives in w1/w2; constrain only w0 here and let Dest24 take the rest
            w0 = ' & '.join(per[0]) or 'w0_all'
            mn, act = CF[name]
            print(':%s Dest24 is %s ; Dest24 { %s Dest24; }' % (mn, w0, act))
            emitted += 1
            continue
        parts, ops = [], []
        for w in range(ntok):
            c = per[w]
            if c:
                parts.append(' & '.join(c))
            else:
                # unconstrained word: reference it so the token is consumed,
                # and show it, since only a referenced field may be an operand
                parts.append('w%d_all' % w)
                if w > 0:
                    ops.append('w%d_all' % w)
        print(':t%s %s is %s { }' % (name.replace('_', '.'),
                                     ', '.join(ops) if ops else '',
                                     ' ; '.join(parts)))
        emitted += 1
    sys.stderr.write('emitted %d constructors\n' % emitted)

main()
