#!/usr/bin/env python3
"""Generate the SHARC SLEIGH spec from tools/sharc_visa_tables.py.

Hand-writing 47 constructors would drift from the transcription the moment
either changed. This emits them, so the table stays the single source of
truth and regenerating is the way to pick up encoding fixes.

Only control-flow types carry semantics: p-code is not needed for
disassembly, call graphs or xrefs, which is all this is for. Everything else
decodes to the right LENGTH and prints its operands, which is what stops a
walk desyncing.

Addressing: code addresses are 16-bit short-word units, so a program is
imported at byte base 2*<word address> and branch targets are doubled here.
A wordsize=2 space would be the natural spelling and silently matches
nothing -- see the module commit message.

    uv run python tools/ghidra/gen-sharc-slaspec.py > tools/ghidra/SHARC/data/languages/sharc.slaspec
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import sharc_visa_tables as T

HEAD = '''# SLEIGH specification for Analog Devices SHARC+ (ADSP-2156x) VISA.
# GENERATED by tools/ghidra/gen-sharc-slaspec.py -- do not edit by hand.
# Encodings come from tools/sharc_visa_tables.py (transcribed from the
# SHARC+ Core Programming Reference at 400 DPI). See that file for which
# entries are confirmed and which are not.
#
# A 48-bit instruction is three 16-bit words, each LITTLE-endian in memory,
# concatenated MOST-SIGNIFICANT WORD FIRST:
#     w0,w1,w2 = unpack('<3H'); insn = (w0<<32)|(w1<<16)|w2
# so insn bit N maps to w0 bit N-32, w1 bit N-16, w2 bit N.

define endian=little;
define alignment=2;

define space ram      type=ram_space      size=4 default;
define space register type=register_space size=4;

define register offset=0x00 size=4 [ PC ];
define register offset=0x10 size=4 [ R0  R1  R2  R3  R4  R5  R6  R7
                                     R8  R9  R10 R11 R12 R13 R14 R15 ];
define register offset=0x50 size=4 [ I0 I1 I2 I3 I4 I5 I6 I7 ];
define register offset=0x70 size=4 [ M0 M1 M2 M3 M4 M5 M6 M7 ];
'''

def tokens():
    out = []
    for w in (0, 1, 2):
        out.append('define token w%d (16)' % w)
        out.append('    w%d_all = (0,15)' % w)
        for b in range(16):
            out.append('    w%d_%d = (%d,%d)' % (w, b, b, b))
        out.append(';')
    return '\n'.join(out)

def word_of(bit, nbits):
    """-> (token index, bit position within that 16-bit word)."""
    top = nbits - 1                     # e.g. 47 for a 48-bit instruction
    w = (top - bit) // 16               # 0 = most significant word
    return w, bit % 16

def constraints(entry):
    """-> list per token index of constraint strings."""
    n = entry['bits']
    mask, val = entry['opcode_mask'], entry['opcode_value']
    per = {0: [], 1: [], 2: []}
    for bit in range(n):
        if (mask >> bit) & 1:
            w, p = word_of(bit, n)
            per[w].append('w%d_%d=%d' % (w, p, (val >> bit) & 1))
    return per

def main():
    print(HEAD)
    print(tokens())
    print()
    print('# 24-bit absolute target, high 8 bits in w1 and low 16 in w2,')
    print('# doubled to turn a short-word address into this space\'s byte address.')
    print('Dest24: reloc is w1_15=0 & w1_14=0 & w1_13=0 & w1_12=0 & w1_11=0 & '
          'w1_10=0 & w1_9=0 & w1_8=0 & w1_all ; w2_all')
    print('    [ reloc = ((w1_all & 0xff) << 17) + (w2_all << 1); ] { export *:4 reloc; }')
    print()
    CF = {'25a_direct': ('cjump', 'call'), '25a_pcrel': ('cjump_pc', 'goto')}
    emitted = 0
    for e in T.TYPES:
        name = e['name']
        if e.get('uncertain'):
            continue
        if not e.get('opcode_mask'):
            continue
        n = e['bits']
        per = constraints(e)
        ntok = n // 16
        if name in CF:
            # target lives in w1/w2; constrain only w0 here and let Dest24 take the rest
            w0 = ' & '.join(per[0]) or 'w0_all'
            mn, act = CF[name]
            print(':%s Dest24 is %s ; Dest24 { %s Dest24; }' % (mn, w0, act))
            emitted += 1
            continue
        parts, ops = [], []
        for w in range(ntok):
            c = per[w]
            if c:
                parts.append(' & '.join(c))
            else:
                # unconstrained word: reference it so the token is consumed,
                # and show it, since only a referenced field may be an operand
                parts.append('w%d_all' % w)
                if w > 0:
                    ops.append('w%d_all' % w)
        print(':t%s %s is %s { }' % (name.replace('_', '.'),
                                     ', '.join(ops) if ops else '',
                                     ' ; '.join(parts)))
        emitted += 1
    sys.stderr.write('emitted %d constructors\n' % emitted)

main()
